Default: &defaults
  database: matrizerWeb.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: matrizerWeb_test.sqlite3
  <<: *defaults

Staging:
  database: matrizerWeb_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: matrizerWeb_production.sqlite3
  poolsize: 100
  <<: *defaults
